// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnoJ2GBj2wkMr_DzIOPD_hc_KwmkEfHpk',
    appId: '1:702446714552:web:61f66631302d205005fe4d',
    messagingSenderId: '702446714552',
    projectId: 'reviewgourmet-fire',
    authDomain: 'reviewgourmet-fire.firebaseapp.com',
    storageBucket: 'reviewgourmet-fire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYMf_9c1SooWNR1zg1FxIleNS8Ad4EiXc',
    appId: '1:702446714552:android:29d364ff0e55b09e05fe4d',
    messagingSenderId: '702446714552',
    projectId: 'reviewgourmet-fire',
    storageBucket: 'reviewgourmet-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANf50yVRycNZ9L-BBVSjNcXZ_Q3lS39AM',
    appId: '1:702446714552:ios:6f856564b355d8d105fe4d',
    messagingSenderId: '702446714552',
    projectId: 'reviewgourmet-fire',
    storageBucket: 'reviewgourmet-fire.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANf50yVRycNZ9L-BBVSjNcXZ_Q3lS39AM',
    appId: '1:702446714552:ios:1b08bfcb9b9a809905fe4d',
    messagingSenderId: '702446714552',
    projectId: 'reviewgourmet-fire',
    storageBucket: 'reviewgourmet-fire.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
